// AI Provider 层：统一封装 OpenAI 兼容模型调用。
// 智谱/GLM 使用 GLM_API_KEY（推荐）或旧变量 ZHIPU_API_KEY；豆包使用 ARK_API_KEY。
const DEFAULT_GLM_BASE_URL = 'https://open.bigmodel.cn/api/paas/v4';
const DEFAULT_DOUBAO_BASE_URL = 'https://ark.cn-beijing.volces.com/api/v3';
const trimSlash = (value) => String(value || '').replace(/\/+$/, '');
const provider = () => { const value = String(process.env.AI_PROVIDER || 'glm').trim().toLowerCase(); return value === 'doubao' ? 'doubao' : value === 'mock' ? 'mock' : 'glm'; };
const key = (name) => name === 'doubao' ? process.env.ARK_API_KEY : (process.env.GLM_API_KEY || process.env.ZHIPU_API_KEY);
const endpoint = (name) => { const base = trimSlash(name === 'doubao' ? (process.env.ARK_BASE_URL || DEFAULT_DOUBAO_BASE_URL) : (process.env.GLM_BASE_URL || DEFAULT_GLM_BASE_URL)); return base.endsWith('/chat/completions') ? base : base + '/chat/completions'; };
export const currentProvider = provider;
export const currentModel = () => provider() === 'doubao' ? (process.env.DOUBAO_MODEL || 'doubao-1-5-lite-32k-250115') : (process.env.AI_MODEL || process.env.GLM_MODEL || 'glm-4.5-flash');
export const fastModel = () => provider() === 'doubao' ? (process.env.DOUBAO_MODEL || 'doubao-1-5-lite-32k-250115') : (process.env.GLM_FAST_MODEL || process.env.GLM_MODEL || process.env.AI_MODEL || 'glm-4.5-flash');
export const isConfigured = () => provider() !== 'mock' && Boolean(key(provider()));
export function safeJson(text) { if (!text) return null; const value = String(text).trim(); try { return JSON.parse(value); } catch { const start = value.indexOf('{'); const end = value.lastIndexOf('}'); if (start >= 0 && end > start) { try { return JSON.parse(value.slice(start, end + 1)); } catch { return null; } } return null; } }
export function extractArray(obj) { if (Array.isArray(obj)) return obj; if (obj && typeof obj === 'object') { for (const name of ['questions', 'result', 'data', 'items', 'list']) if (Array.isArray(obj[name])) return obj[name]; const arrays = Object.values(obj).filter(Array.isArray); if (arrays.length === 1) return arrays[0]; } return null; }
async function request(body, name) { const apiKey = key(name); if (!apiKey) throw new Error((name === 'doubao' ? '豆包' : '智谱') + ' API Key 未配置（请检查 ' + (name === 'doubao' ? 'ARK_API_KEY' : 'GLM_API_KEY 或 ZHIPU_API_KEY') + '）'); const response = await fetch(endpoint(name), { method: 'POST', headers: { 'Content-Type': 'application/json', Authorization: 'Bearer ' + apiKey }, body: JSON.stringify(body), signal: AbortSignal.timeout(50000) }); if (!response.ok) throw new Error((name === 'doubao' ? '豆包' : '智谱') + ' API ' + response.status + ': ' + (await response.text()).slice(0, 300)); const data = await response.json(); const content = data?.choices?.[0]?.message?.content; if (!content) throw new Error('AI API 返回为空'); return String(content); }
export async function vision(prompt, dataUrl, { maxTokens = 1800, model } = {}) { if (!isConfigured()) throw new Error('AI 未配置（请设置 AI_PROVIDER=glm 与 GLM_API_KEY）'); const name = provider(); return request({ model: model || process.env.GLM_VISION_MODEL || process.env.OCR_MODEL || currentModel(), messages: [{ role: 'user', content: [{ type: 'text', text: prompt }, { type: 'image_url', image_url: { url: dataUrl } }] }], max_tokens: maxTokens, stream: false }, name); }
export async function chat(messages, { temperature = 0.7, json = false, maxTokens = 1024, model } = {}) { if (!isConfigured()) throw new Error('AI 未配置（请设置 AI_PROVIDER=glm 与 GLM_API_KEY）'); const name = provider(); const body = { model: model || currentModel(), messages, temperature, max_tokens: maxTokens, stream: false }; if (json) body.response_format = { type: 'json_object' }; return request(body, name); }
