import express from 'express';
import multer from 'multer';
import * as uploadController from '../controllers/universityUploadController.js';
import authMiddleware from '../middleware/auth.js';
import * as controller from '../controllers/universityController.js';
const router = express.Router();
const upload = multer({ storage: multer.memoryStorage(), limits: { fileSize: 10 * 1024 * 1024 } });
router.use(authMiddleware);
router.get('/workspace', controller.getWorkspace);
router.post('/files/upload', upload.single('file'), uploadController.uploadFile);
router.post('/courses', controller.createCourse);
router.patch('/courses/:id', controller.updateCourse);
router.post('/assignments', controller.createAssignment);
router.patch('/assignments/:id', controller.updateAssignment);
router.post('/plans', controller.createPlan);
router.patch('/plans/:id', controller.updatePlan);
router.delete('/plans/:id', controller.deletePlan);
router.delete('/files/:id', controller.deleteFile);
export default router;
