import { useEffect, useState } from 'react';
import { AlertTriangle, Bell, BookOpen, Calculator, CheckCircle2, Clock3, GraduationCap, TrendingUp } from 'lucide-react';
import { universityService } from '@/services/universityService';

type CourseStat = { course: any; grade?: any; studySeconds: number; predictedScore: number | null; risk: boolean };
const minutes = (seconds: number) => Math.round(seconds / 60);
export default function UniversityAnalytics() {
  const [data, setData] = useState<any>(null);
  const [error, setError] = useState('');
  const [grade, setGrade] = useState<any>({ semester: '本学期' });
  const [saving, setSaving] = useState(false);
  const [loading, setLoading] = useState(true);
  const load = async () => { setLoading(true); try { await universityService.refreshNotifications(); const res: any = await universityService.analytics(); setData(res.data); } catch (e: any) { setError(e?.error?.message || '学习分析加载失败'); } finally { setLoading(false); } };
  useEffect(() => { load(); }, []);
  const update = (key: string, raw: string) => setGrade((prev: any) => ({ ...prev, [key]: raw === '' ? null : (key === 'semester' ? raw : Number(raw)) }));
  const save = async () => { if (!grade.courseId) { setError('请先选择课程'); return; } setSaving(true); setError(''); try { await universityService.saveGrade({ ...grade, credits: Number(grade.credits) || 0 }); setGrade({ courseId: grade.courseId, semester: grade.semester || '本学期' }); await load(); } catch (e: any) { setError(e?.error?.message || '成绩保存失败'); } finally { setSaving(false); } };
  if (loading && !data) return <div className="mx-auto max-w-7xl p-6 text-center text-gray-400">正在加载成绩与学习分析…</div>;
  if (!data) return <div className="mx-auto max-w-7xl p-6 text-center text-rose-500">{error || '学习分析暂不可用'}</div>;
  const stats: CourseStat[] = data.courseStats || [];
  const selected = stats.find((item) => item.course.id === grade.courseId);
  return <div className="mx-auto max-w-7xl space-y-5 p-3 pb-24 sm:p-6">
    <header className="university-hero rounded-2xl p-5 text-white sm:p-7"><div className="flex items-center gap-2 text-sm text-indigo-100"><GraduationCap size={18}/> UNIVERSITY ANALYTICS</div><h1 className="mt-2 text-2xl font-black sm:text-4xl">成绩与学习分析</h1><p className="mt-2 text-sm text-indigo-100">在这里直接录入每门课程的平时、期中、期末成绩和学分。</p></header>
    {error && <div className="rounded-lg border border-amber-300 bg-amber-50 p-3 text-sm text-amber-700">{error}</div>}
    <section className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><div className="card p-4"><Clock3 className="text-indigo-600"/><b className="mt-2 block text-2xl">{minutes(data.totalStudySeconds)} 分钟</b><span className="text-xs text-gray-500">累计学习时长</span></div><div className="card p-4"><CheckCircle2 className="text-emerald-600"/><b className="mt-2 block text-2xl">{data.assignmentRate}%</b><span className="text-xs text-gray-500">作业完成率</span></div><div className="card p-4"><BookOpen className="text-cyan-600"/><b className="mt-2 block text-2xl">{data.planRate}%</b><span className="text-xs text-gray-500">计划完成率</span></div><div className="card p-4"><Calculator className="text-amber-600"/><b className="mt-2 block text-2xl">{data.gpa ?? '—'}</b><span className="text-xs text-gray-500">估算 GPA</span></div></section>
    <section className="card border-2 border-indigo-200 p-4 sm:p-6"><h2 className="text-lg font-black text-indigo-800">录入课程成绩</h2><p className="mt-1 text-sm text-gray-500">先选择课程，再填写成绩；保存后会自动计算预测成绩和 GPA。</p>{stats.length ? <div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-6"><select className="input h-10 lg:col-span-2" value={grade.courseId || ''} onChange={(e) => { const item = stats.find((x) => x.course.id === e.target.value); setGrade({ courseId: e.target.value, semester: item?.grade?.semester || '本学期', usual: item?.grade?.usual ?? '', midterm: item?.grade?.midterm ?? '', final: item?.grade?.final ?? '', credits: item?.grade?.credits ?? '' }); }}><option value="">请选择课程</option>{stats.map((item) => <option key={item.course.id} value={item.course.id}>{item.course.name}</option>)}</select><input className="input h-10" type="number" min="0" max="100" placeholder="平时成绩" value={grade.usual ?? ''} onChange={(e) => update('usual', e.target.value)}/><input className="input h-10" type="number" min="0" max="100" placeholder="期中成绩" value={grade.midterm ?? ''} onChange={(e) => update('midterm', e.target.value)}/><input className="input h-10" type="number" min="0" max="100" placeholder="期末成绩" value={grade.final ?? ''} onChange={(e) => update('final', e.target.value)}/><input className="input h-10" type="number" min="0" placeholder="学分" value={grade.credits ?? ''} onChange={(e) => update('credits', e.target.value)}/><input className="input h-10" placeholder="学期" value={grade.semester ?? ''} onChange={(e) => update('semester', e.target.value)}/><button className="btn-primary h-10 lg:col-span-2" disabled={saving} onClick={save}>{saving ? '保存中…' : '保存成绩'}</button></div> : <div className="mt-4 rounded-lg bg-amber-50 p-4 text-sm text-amber-700">还没有课程。请先到<a className="font-bold underline" href="/university">大学工作台</a>添加课程，然后回来录入成绩。</div>}{selected && <div className="mt-4 rounded-lg bg-indigo-50 p-3 text-sm text-indigo-800">当前课程：<b>{selected.course.name}</b> · 已保存预测成绩：<b>{selected.predictedScore ?? '—'}</b></div>}</section>
    <section className="card overflow-hidden"><div className="border-b p-4"><h2 className="flex items-center gap-2 font-bold"><TrendingUp size={18} className="text-indigo-600"/>每门课程分析</h2></div><div className="divide-y">{stats.map((item) => <div key={item.course.id} className="grid gap-2 p-4 sm:grid-cols-4"><div><b>{item.course.name}</b><div className="text-xs text-gray-500">掌握度 {item.course.mastery}% · 学习 {minutes(item.studySeconds)} 分钟</div></div><div className={item.risk ? 'flex items-center gap-1 text-sm text-rose-600' : 'text-sm text-emerald-600'}>{item.risk && <AlertTriangle size={15}/>} {item.risk ? '需要优先复习' : '进度正常'}</div><div className="text-sm">预测成绩：<b>{item.predictedScore ?? '—'}</b></div><div className="text-sm">学分：{item.grade?.credits ?? '—'} · 学期：{item.grade?.semester ?? '—'}</div></div>)}</div></section>
    <section className="card p-4"><h2 className="flex items-center gap-2 font-bold"><Bell size={18} className="text-rose-500"/>作业提醒</h2>{data.notifications?.length ? <div className="mt-3 space-y-2">{data.notifications.map((n: any) => <div key={n.id} className="rounded-lg bg-rose-50 p-3 text-sm text-rose-700">{n.title}：{n.message}</div>)}</div> : <p className="mt-3 text-sm text-gray-500">暂无 3 天内到期的未完成作业。</p>}</section>
  </div>;
}
