import { useEffect, useMemo, useState } from 'react';
import { BookOpen, CalendarDays, CheckCircle2, Clock3, FileText, GraduationCap, Lightbulb, Plus, Send, Sparkles, Trash2, Upload, X } from 'lucide-react';
import { aiService } from '@/services/aiService';
import { StudyReward } from '@/components/StudyReward';
import { universityService } from '@/services/universityService';
import * as XLSX from 'xlsx';

type Course = { id: string; name: string; teacher: string; color: string; mastery: number; nextExam: string };
type Assignment = { id: string; title: string; course: string; dueDate: string; completed: boolean };
type Plan = { id: string; title: string; day: string; completed: boolean };
type Schedule = { id: string; title: string; weekday: number; startTime: string; endTime: string; room?: string; teacher?: string };
type FileNote = { id: string; name: string; mimeType: string; size: number; storageUrl: string; category: string; courseId?: string; aiSummary?: string };
function daysUntil(date: string) { if (!date) return null; return Math.max(0, Math.ceil((new Date(date).getTime() - Date.now()) / 86400000)); }

export default function UniversityHub() {
  const [courses, setCourses] = useState<Course[]>([]);
  const [assignments, setAssignments] = useState<Assignment[]>([]);
  const [plans, setPlans] = useState<Plan[]>([]);
  const [schedules, setSchedules] = useState<Schedule[]>([]);
  const [scheduleForm, setScheduleForm] = useState({ title: '', weekday: 1, startTime: '08:00', endTime: '09:40', room: '', teacher: '' });
  const [files, setFiles] = useState<FileNote[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');
  const [uploading, setUploading] = useState(false);
  const [summarizingFile, setSummarizingFile] = useState('');
  const [courseName, setCourseName] = useState('');
  const [courseTeacher, setCourseTeacher] = useState('');
  const [fileCourseId, setFileCourseId] = useState('');
  const [fileCategory, setFileCategory] = useState('course-material');
  const [assignment, setAssignment] = useState({ title: '', course: '', due: '' });
  const [planTitle, setPlanTitle] = useState('');
  const [planDay, setPlanDay] = useState('今天');
  const [summaryInput, setSummaryInput] = useState('');
  const [summary, setSummary] = useState('');
  const [essayPrompt, setEssayPrompt] = useState('');
  const [essayAnswer, setEssayAnswer] = useState('');
  const [aiLoading, setAiLoading] = useState(false);
  const [reward, setReward] = useState<{ title: string; message: string; icon: string } | null>(null);
  useEffect(() => { universityService.workspace().then((res: any) => { const data = res.data || {}; setCourses((data.courses || []).map((course: any) => ({ ...course, nextExam: course.examDate ? String(course.examDate).slice(0, 10) : '' }))); setAssignments(data.assignments || []); setPlans(data.plans || []); setFiles(data.files || []); setSchedules(data.schedules || []); }).catch((e: any) => setError(e?.error?.message || '无法同步大学学习数据，请确认已登录')).finally(() => setLoading(false)); }, []);
  const addCourse = async () => { if (!courseName.trim()) return; try { const res: any = await universityService.createCourse({ name: courseName.trim(), teacher: courseTeacher.trim() }); setCourses((prev) => [...prev, { ...res.data, nextExam: '' }]); setCourseName(''); setCourseTeacher(''); } catch (e: any) { setError(e?.error?.message || '课程保存失败'); } };
  const removeCourse = async (id: string) => { if (!window.confirm('确定删除这门课程？相关掌握度记录将保留在其他系统中。')) return; try { await universityService.deleteCourse(id); setCourses((prev) => prev.filter((item) => item.id !== id)); } catch (e: any) { setError(e?.error?.message || '课程删除失败'); } };
  const changeCourse = async (id: string, patch: Partial<Course>) => { try { const payload: any = { ...patch }; if (payload.nextExam !== undefined) { payload.examDate = payload.nextExam || null; delete payload.nextExam; } const res: any = await universityService.updateCourse(id, payload); setCourses((prev) => prev.map((course) => course.id === id ? { ...course, ...res.data, nextExam: res.data.examDate ? String(res.data.examDate).slice(0, 10) : '' } : course)); } catch (e: any) { setError(e?.error?.message || '课程更新失败'); } };
  const addSchedule = async () => { if (!scheduleForm.title.trim()) return; try { const res: any = await universityService.createSchedule(scheduleForm); setSchedules((prev) => [...prev, res.data].sort((a, b) => a.weekday - b.weekday || a.startTime.localeCompare(b.startTime))); setScheduleForm({ title: '', weekday: 1, startTime: '08:00', endTime: '09:40', room: '', teacher: '' }); } catch (e: any) { setError(e?.error?.message || '课表保存失败'); } };
  const importSchedules = async (file: File) => { try { if (file.name.toLowerCase().endsWith('.ics')) { const text = await file.text(); const blocks = text.split('BEGIN:VEVENT').slice(1); for (const block of blocks) { const get = (key: string) => block.match(new RegExp('\\n' + key + '[:;]([^\\n]+)'))?.[1]?.trim() || ''; const start = get('DTSTART').replace(/\\D/g, ''); const weekday = start ? (new Date(start.slice(0, 4) + '-' + start.slice(4, 6) + '-' + start.slice(6, 8)).getDay() || 7) : 1; await universityService.createSchedule({ title: get('SUMMARY') || '导入课程', weekday, startTime: start.slice(9, 13).replace(/(\\d{2})(\\d{2})/, '$1:$2') || '08:00', endTime: '09:40', room: get('LOCATION') }); } } else { const workbook = XLSX.read(await file.arrayBuffer(), { type: 'array' }); const rows = XLSX.utils.sheet_to_json<any>(workbook.Sheets[workbook.SheetNames[0]]); for (const row of rows) await universityService.createSchedule({ title: row.课程 || row.课程名称 || row.title || '导入课程', weekday: Number(row.星期 || row.weekday || 1), startTime: row.开始时间 || row.startTime || '08:00', endTime: row.结束时间 || row.endTime || '09:40', room: row.教室 || row.room || '', teacher: row.教师 || row.teacher || '' }); } const res: any = await universityService.workspace(); setSchedules(res.data.schedules || []); } catch (e: any) { setError(e?.error?.message || '课表导入失败，请检查 Excel 列名或 ICS 文件格式'); } };
  const removeSchedule = async (id: string) => { try { await universityService.deleteSchedule(id); setSchedules((prev) => prev.filter((item) => item.id !== id)); } catch (e: any) { setError(e?.error?.message || '课表删除失败'); } };
  const addAssignment = async () => { if (!assignment.title.trim() || !assignment.due) return; try { const res: any = await universityService.createAssignment({ title: assignment.title, course: assignment.course, dueDate: assignment.due }); setAssignments((prev) => [...prev, res.data]); setAssignment({ title: '', course: '', due: '' }); } catch (e: any) { setError(e?.error?.message || '作业保存失败'); } };
  const removeAssignment = async (id: string) => { try { await universityService.deleteAssignment(id); setAssignments((prev) => prev.filter((item) => item.id !== id)); } catch (e: any) { setError(e?.error?.message || '作业删除失败'); } };
  const toggleAssignment = async (id: string) => { const item = assignments.find((entry) => entry.id === id); if (!item) return; try { const res: any = await universityService.updateAssignment(id, { completed: !item.completed }); setAssignments((prev) => prev.map((entry) => entry.id === id ? res.data : entry)); if (res.data.completed) setReward({ title: '作业完成！', message: '把截止日期变成完成记录，做得很好。', icon: '✅' }); } catch (e: any) { setError(e?.error?.message || '作业更新失败'); } };
  const addPlan = async () => { if (!planTitle.trim()) return; try { const res: any = await universityService.createPlan({ title: planTitle.trim(), day: planDay }); setPlans((prev) => [res.data, ...prev]); setPlanTitle(''); } catch (e: any) { setError(e?.error?.message || '计划保存失败'); } };
  const togglePlan = async (id: string) => { const item = plans.find((entry) => entry.id === id); if (!item) return; try { const res: any = await universityService.updatePlan(id, { completed: !item.completed }); setPlans((prev) => prev.map((entry) => entry.id === id ? res.data : entry)); } catch (e: any) { setError(e?.error?.message || '计划更新失败'); } };
  const removePlan = async (id: string) => { try { await universityService.deletePlan(id); setPlans((prev) => prev.filter((item) => item.id !== id)); } catch (e: any) { setError(e?.error?.message || '计划删除失败'); } };
  const addFiles = async (list: FileList | null) => { if (!list?.length) return; setError(''); setUploading(true); try { for (const file of Array.from(list)) { const res: any = await universityService.uploadFile(file, fileCategory, fileCourseId || undefined); setFiles((prev) => [res.data, ...prev]); } } catch (e: any) { setError(e?.error?.message || '文件上传失败，请确认 Blob 存储已连接到 Production 项目'); } finally { setUploading(false); } };
  const summarizeFile = async (id: string) => { setSummarizingFile(id); setError(''); try { const res: any = await universityService.summarizeFile(id); setFiles((prev) => prev.map((item) => item.id === id ? res.data.file : item)); } catch (e: any) { setError(e?.error?.message || '资料总结失败'); } finally { setSummarizingFile(''); } };
  const removeFile = async (id: string) => { try { await universityService.deleteFile(id); setFiles((prev) => prev.filter((item) => item.id !== id)); } catch (e: any) { setError(e?.error?.message || '文件删除失败'); } };
  const askAI = async (kind: 'summary' | 'essay') => { const input = kind === 'summary' ? summaryInput : essayPrompt; if (!input.trim()) return; setAiLoading(true); try { const res = await aiService.chat(kind === 'summary' ? '请把下面的课程课件/笔记整理成大学生容易复习的结构：先给出三行摘要，再列核心概念、重点例子、容易混淆的地方和5道自测题。内容必须基于原文，不要编造。\n\n' + input : '你是一名大学论文写作助手。根据下面的论文题目/要求，给出研究问题、文章结构、论证思路、资料检索关键词和写作注意事项。不要代写整篇论文，帮助学生形成自己的观点。\n\n' + input); const answer = res.data.answer || ''; kind === 'summary' ? setSummary(answer) : setEssayAnswer(answer); } catch { kind === 'summary' ? setSummary('AI 暂时不可用，请检查网络或稍后重试。') : setEssayAnswer('AI 暂时不可用，请检查网络或稍后重试。'); } finally { setAiLoading(false); } };
  const upcoming = useMemo(() => assignments.filter((item) => !item.completed).sort((a, b) => a.dueDate.localeCompare(b.dueDate)).slice(0, 5), [assignments]);
  const weekDays = ['周一', '周二', '周三', '周四', '周五', '周六', '周日'];
  if (loading) return <div className="university-hub mx-auto max-w-7xl p-6 text-center text-gray-400">正在同步大学学习数据…</div>;
  return <div className="university-hub mx-auto max-w-7xl space-y-5 p-3 pb-24 sm:p-6">
    {error && <div className="rounded-lg border border-amber-300 bg-amber-50 p-3 text-sm text-amber-700">{error}</div>}
    <StudyReward open={!!reward} title={reward?.title || ''} message={reward?.message} icon={reward?.icon} onClose={() => setReward(null)} />
    <header className="university-hero rounded-2xl p-5 text-white sm:p-7"><div className="flex flex-wrap items-start justify-between gap-4"><div><div className="mb-2 flex items-center gap-2 text-sm font-semibold text-indigo-100"><GraduationCap size={18} /> UNIVERSITY STUDY HUB</div><h1 className="text-2xl font-black sm:text-4xl">我的大学学习工作台</h1><p className="mt-2 max-w-2xl text-sm text-indigo-100">把课程、资料、作业和 AI 工具放在一个地方。先规划，再学习，最后复盘。</p></div><div className="rounded-xl border border-white/20 bg-white/10 p-4 text-center"><div className="text-xs text-indigo-100">本周完成</div><div className="text-3xl font-black">{plans.filter((item) => item.completed).length}<span className="text-base"> / {plans.length}</span></div></div></div></header>
    <section className="grid gap-4 lg:grid-cols-[1.35fr_1fr]">
      <div className="card p-4 sm:p-5"><div className="mb-4 flex items-center justify-between"><h2 className="flex items-center gap-2 font-bold"><BookOpen size={18} className="text-indigo-600" />课程与掌握度</h2><div className="flex flex-wrap gap-2"><input className="input h-9 max-w-[150px]" value={courseName} onChange={(e) => setCourseName(e.target.value)} placeholder="添加课程"/><input className="input h-9 max-w-[130px]" value={courseTeacher} onChange={(e) => setCourseTeacher(e.target.value)} placeholder="教师（可选）"/><button className="btn-primary px-3 py-1.5" onClick={addCourse}><Plus size={15}/></button></div></div><div className="space-y-3">{courses.map((course) => <div key={course.id} className="rounded-xl border border-indigo-100 p-3 dark:border-indigo-900/60"><div className="flex items-center justify-between gap-2"><div className="flex min-w-0 items-center gap-2"><span className="h-3 w-3 shrink-0 rounded-full" style={{ background: course.color }}/><b className="truncate">{course.name}</b></div><span className="flex items-center gap-2 text-sm font-bold text-indigo-600">{course.mastery}% <button type="button" onClick={() => removeCourse(course.id)} className="text-gray-300 hover:text-rose-500" aria-label="删除课程"><X size={14}/></button></span></div><div className="mt-2 h-2 overflow-hidden rounded-full bg-indigo-50"><div className="h-full rounded-full bg-indigo-500" style={{ width: course.mastery + '%' }}/></div><div className="mt-2 flex flex-wrap gap-2 text-xs text-gray-500"><label>掌握度 <input type="range" min="0" max="100" value={course.mastery} onChange={(e) => changeCourse(course.id, { mastery: Number(e.target.value) })} /></label><input className="h-7 w-28 rounded border px-2" value={course.nextExam} onChange={(e) => changeCourse(course.id, { nextExam: e.target.value })} type="date"/><span>{course.nextExam ? '距考试 ' + (daysUntil(course.nextExam) ?? 0) + ' 天' : '设置考试日期'}</span></div></div>)}</div></div>
      <div className="card p-4 sm:p-5"><h2 className="mb-3 flex items-center gap-2 font-bold"><CalendarDays size={18} className="text-indigo-600"/>课程表 / 学期计划</h2><div className="mb-3 grid gap-2 sm:grid-cols-3"><input className="input h-9" placeholder="课程名称" value={scheduleForm.title} onChange={(e) => setScheduleForm({ ...scheduleForm, title: e.target.value })}/><select className="h-9 rounded border px-2 text-sm" value={scheduleForm.weekday} onChange={(e) => setScheduleForm({ ...scheduleForm, weekday: Number(e.target.value) })}>{weekDays.map((day, i) => <option key={day} value={i + 1}>{day}</option>)}</select><button className="btn-primary h-9" onClick={addSchedule}><Plus size={15}/>添加课表</button><label className="btn-secondary h-9 cursor-pointer">导入 Excel/ICS<input className="hidden" type="file" accept=".xlsx,.xls,.ics" onChange={(e) => { if (e.target.files?.[0]) importSchedules(e.target.files[0]); e.currentTarget.value = ''; }}/></label><input className="input h-9" type="time" value={scheduleForm.startTime} onChange={(e) => setScheduleForm({ ...scheduleForm, startTime: e.target.value })}/><input className="input h-9" type="time" value={scheduleForm.endTime} onChange={(e) => setScheduleForm({ ...scheduleForm, endTime: e.target.value })}/><input className="input h-9" placeholder="教室 / 教师（可选）" value={scheduleForm.room} onChange={(e) => setScheduleForm({ ...scheduleForm, room: e.target.value })}/></div><div className="grid grid-cols-7 gap-1 text-center text-[10px] sm:text-xs">{weekDays.map((day, i) => <div key={day} className="min-h-24 rounded border border-indigo-100 p-1 text-left dark:border-indigo-900/50"><div className="mb-1 rounded bg-indigo-50 py-1 text-center font-bold text-indigo-700 dark:bg-indigo-950/50 dark:text-indigo-200">{day}</div>{schedules.filter((item) => item.weekday === i + 1).map((item) => <div key={item.id} className="mb-1 rounded bg-indigo-100 p-1 text-indigo-700 dark:bg-indigo-900/50 dark:text-indigo-200"><div className="font-bold">{item.title}</div><div>{item.startTime}–{item.endTime}</div>{item.room && <div>{item.room}</div>}<button onClick={() => removeSchedule(item.id)} className="mt-1 text-rose-500">删除</button></div>)}</div>)}</div>{!schedules.length && <p className="mt-3 text-center text-xs text-gray-400">添加真实课程后，课表会在电脑和手机同步。</p>}</div>
    </section>
    <section className="grid gap-4 lg:grid-cols-2">
      <div className="card p-4 sm:p-5"><h2 className="mb-3 flex items-center gap-2 font-bold"><Clock3 size={18} className="text-rose-500"/>作业截止提醒</h2><div className="mb-3 grid gap-2 sm:grid-cols-[1fr_120px_130px_auto]"><input className="input h-9" placeholder="作业名称" value={assignment.title} onChange={(e) => setAssignment({ ...assignment, title: e.target.value })}/><input className="input h-9" placeholder="课程" value={assignment.course} onChange={(e) => setAssignment({ ...assignment, course: e.target.value })}/><input className="input h-9" type="date" value={assignment.due} onChange={(e) => setAssignment({ ...assignment, due: e.target.value })}/><button className="btn-primary h-9 px-3" onClick={addAssignment}><Plus size={15}/></button></div><div className="space-y-2">{upcoming.length ? upcoming.map((item) => <div key={item.id} className="flex items-center gap-2 rounded-lg bg-rose-50 p-2 text-sm dark:bg-rose-950/20"><button onClick={() => toggleAssignment(item.id)}><CheckCircle2 size={17} className="text-gray-300"/></button><span className="min-w-0 flex-1 truncate">{item.title}<small className="ml-2 text-gray-400">{item.course}</small></span><b className="shrink-0 text-xs text-rose-600">{daysUntil(item.dueDate) === 0 ? '今天' : daysUntil(item.dueDate) + '天后'} <button type="button" onClick={() => removeAssignment(item.id)} className="ml-1 text-gray-300 hover:text-rose-600" aria-label="删除作业"><X size={13}/></button></b></div>) : <p className="py-5 text-center text-sm text-gray-400">暂无待完成作业</p>}</div></div>
      <div className="card p-4 sm:p-5"><h2 className="mb-3 flex items-center gap-2 font-bold"><CheckCircle2 size={18} className="text-emerald-600"/>本周学习计划看板</h2><div className="mb-3 flex gap-2"><input className="input h-9" placeholder="例如：复习第三章" value={planTitle} onChange={(e) => setPlanTitle(e.target.value)}/><select className="h-9 rounded border px-2 text-sm" value={planDay} onChange={(e) => setPlanDay(e.target.value)}>{['今天', ...weekDays].map((day) => <option key={day}>{day}</option>)}</select><button className="btn-primary px-3" onClick={addPlan}><Plus size={15}/></button></div><div className="grid gap-2 sm:grid-cols-2">{plans.map((item) => <div key={item.id} className={'flex items-center gap-2 rounded-lg border p-2 text-sm ' + (item.completed ? 'opacity-50' : '')}><button onClick={() => togglePlan(item.id)}>{item.completed ? <CheckCircle2 size={17} className="text-emerald-600"/> : <span className="block h-4 w-4 rounded-full border-2"/>}</button><span className="min-w-0 flex-1 truncate">{item.title}<small className="ml-1 text-gray-400">· {item.day}</small></span><button onClick={() => removePlan(item.id)}><Trash2 size={14} className="text-gray-300"/></button></div>)}</div>{!plans.length && <p className="py-5 text-center text-sm text-gray-400">添加本周第一个计划</p>}</div>
    </section>
    <section className="grid gap-4 lg:grid-cols-2">
      <div className="card p-4 sm:p-5"><h2 className="mb-2 flex items-center gap-2 font-bold"><Upload size={18} className="text-cyan-600"/>课程资料与笔记整理</h2><p className="mb-3 text-xs text-gray-500">支持选择 PDF、图片、Word 等文件，上传后可在电脑和手机同步访问。</p><div className="mb-2 grid gap-2 sm:grid-cols-2"><select className="h-9 rounded border px-2 text-sm" value={fileCategory} onChange={(e) => setFileCategory(e.target.value)}><option value="course-material">课程课件</option><option value="note">课堂笔记</option><option value="assignment">作业资料</option><option value="reference">参考资料</option></select><select className="h-9 rounded border px-2 text-sm" value={fileCourseId} onChange={(e) => setFileCourseId(e.target.value)}><option value="">不关联课程</option>{courses.map((course) => <option key={course.id} value={course.id}>{course.name}</option>)}</select></div><label className="flex cursor-pointer items-center justify-center gap-2 rounded-xl border-2 border-dashed border-cyan-300 bg-cyan-50 p-5 text-sm font-semibold text-cyan-700 dark:bg-cyan-950/20"><Upload size={18}/>{uploading ? '正在上传，请稍候…' : '选择课程资料'}<input className="hidden" type="file" multiple accept=".pdf,.doc,.docx,.txt,.md,image/*" disabled={uploading} onChange={(e) => { addFiles(e.target.files); e.currentTarget.value = ''; }}/></label><div className="mt-3 space-y-2">{files.map((file) => <div key={file.id} className="flex items-center gap-2 rounded-lg border p-2 text-sm"><FileText size={16} className="shrink-0 text-cyan-600"/><span className="min-w-0 flex-1 truncate"><a href={file.storageUrl} target="_blank" rel="noreferrer" className="hover:text-cyan-600">{file.name}</a><small className="ml-2 text-gray-400">{Math.round(file.size / 1024)} KB</small></span><button onClick={() => summarizeFile(file.id)} disabled={summarizingFile === file.id} className="text-xs text-indigo-500">{summarizingFile === file.id ? '总结中…' : 'AI总结'}</button>{file.aiSummary && <span className="max-w-[220px] truncate text-xs text-indigo-600">{file.aiSummary}</span>}<button onClick={() => summarizeFile(file.id)} disabled={summarizingFile === file.id} className="text-xs text-indigo-500">{summarizingFile === file.id ? '总结中…' : 'AI总结'}</button>{file.aiSummary && <span className="max-w-[220px] truncate text-xs text-indigo-600">{file.aiSummary}</span>}<button onClick={() => removeFile(file.id)}><X size={15} className="text-gray-400"/></button></div>)}</div></div>
      <div className="card p-4 sm:p-5"><h2 className="mb-2 flex items-center gap-2 font-bold"><Sparkles size={18} className="text-violet-600"/>AI 总结课件</h2><textarea className="input min-h-28" value={summaryInput} onChange={(e) => setSummaryInput(e.target.value)} placeholder="粘贴课件文字、课堂笔记或 PDF 提取的文本…"/><button className="btn-primary mt-2 w-full" disabled={aiLoading} onClick={() => askAI('summary')}>{aiLoading ? 'AI 整理中…' : '生成课程总结'} <Sparkles size={15}/></button>{summary && <div className="mt-3 max-h-60 overflow-auto whitespace-pre-wrap rounded-lg bg-violet-50 p-3 text-sm leading-relaxed dark:bg-violet-950/20">{summary}</div>}</div>
    </section>
    <section className="grid gap-4 lg:grid-cols-2"><div className="card p-4 sm:p-5"><h2 className="mb-2 flex items-center gap-2 font-bold"><FileText size={18} className="text-amber-600"/>论文写作助手</h2><textarea className="input min-h-28" value={essayPrompt} onChange={(e) => setEssayPrompt(e.target.value)} placeholder="输入论文题目、课程要求、字数和截止时间…"/><button className="btn-primary mt-2 w-full" disabled={aiLoading} onClick={() => askAI('essay')}>{aiLoading ? 'AI 思考中…' : '生成论文结构与研究计划'} <Send size={15}/></button>{essayAnswer && <div className="mt-3 max-h-60 overflow-auto whitespace-pre-wrap rounded-lg bg-amber-50 p-3 text-sm leading-relaxed dark:bg-amber-950/20">{essayAnswer}</div>}</div><div className="card p-4 sm:p-5"><h2 className="mb-2 flex items-center gap-2 font-bold"><Lightbulb size={18} className="text-yellow-500"/>专业课知识库</h2><p className="text-sm leading-relaxed text-gray-600 dark:text-gray-300">把课程资料按课程归档，再用“AI 总结课件”生成概念、例题、易错点和自测题。专业课知识点可以继续从「学习」页补充，掌握度会在课程卡片中手动更新。</p><div className="mt-4 grid grid-cols-2 gap-2 text-center text-xs"><div className="rounded-lg bg-indigo-50 p-3 dark:bg-indigo-950/30"><b className="block text-xl text-indigo-600">{courses.length}</b>门课程</div><div className="rounded-lg bg-cyan-50 p-3 dark:bg-cyan-950/30"><b className="block text-xl text-cyan-600">{files.length}</b>份资料</div></div></div></section>
  </div>;
}
